version: '3'
services:
 splunkenterprise:
   hostname: splunkenterprise
   image: splunk/splunk:7.0.0
   restart: always
   environment:
     - RUNAS_UID0=false
     - SPLUNK_UID=1004
     - SPLUNK_GID=1004
     - SPLUNK_START_ARGS=--accept-license
     - SPLUNK_ENABLE_LISTEN=9997
     - SPLUNK_ADD='udp 1514'
   volumes:
     - /opt/splunk/etc:/opt/splunk/etc
     - /opt/splunk/var:/opt/splunk/var
   ports:
     - "8000:8000"
     - "9997:9997"
     - "8088:8088"
     - "1514:1514/udp"
